version: '3.3'

volumes:
  pgdata:

services:
  emailsender:
    image: 'emailsender:latest'
    build:
      context: .
    container_name: emailsender
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: email-db
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    volumes:
      - pgdata:/var/lib/docker/volumes/email-sender-volume/_data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq_email_sender'
    ports:
      - 5673:5673
      - 15673:15673
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge